config/routes.rb
Rails.application.routes.draw do

	# sitemap
	get 'sitemap.xml'  => 'crawlers#google', defaults: { format: 'xml' }
	get 'sitemap.atom' => 'crawlers#naver',  defaults: { format: 'atom' }

	# home
  root 'home#index'

	resources :stores, shallow: true do
		resources :store_errs, only: [:new, :create, :destroy]
	end
	resources :store_errs, only: [:index]
	resources :winners, only: [:index]

	get 'home/change_rounds'
  get 'portals/:id/news' => 'portals#news', as: :news

  devise_for :users, controllers: {
		passwords: "users/passwords",
		registrations: "users/registrations",
		sessions: "users/sessions",
		confirmations: "users/confirmations",
		# unlocks: "users/unlocks",
		# omniauth_callbacks: "users/omniauth_callbacks"
	}

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/store.rb
require 'net/http'

class Store < ActiveRecord::Base
	# Mixins
	include Naver
	include Daum

	# Associations
	has_many :winners
	has_many :ranks, through: :winners
	has_many :store_errs
	
	# Class methods
	def self.save_latlng
		self.without_latlng.each do |r|
			addr = r.addr
			loop do
				latlng = r.get_latlng(addr)
				r.update(lat: latlng[0], lng: latlng[1])
				break if (r.have_latlng? || addr == '')
				r.around = true
				addr = addr.split(' ')[0...-1].join(' ') # except addr last element
			end
		end
	end

	def self.without_latlng
		where("NOT (lat >= #{KOREA_LAT_RANGE[:min]} AND lat <= #{KOREA_LAT_RANGE[:max]} AND lng >= #{KOREA_LNG_RANGE[:min]} AND lng <= #{KOREA_LNG_RANGE[:max]})")
	end

	def self.last_updated_at
		limit(1).order(updated_at: :desc).pluck(:updated_at)[0]
	end

	def self.ping(offset)
		header = {
			"User-agent" => "request",
			"Host" => "apis.naver.com",
			"Progma" => "no-cache",
			"Content-type" => "application/x-www-form-urlencoded",
			"Accept" => "*/*",
			"Authorization" => "Bearer " + Naver::SYNDICATION_KEY
		}

		uri = URI.parse('https://apis.naver.com/crawl/nsyndi/v2')

		http = Net::HTTP.new(uri.host, uri.port)
		http.use_ssl = true

		atom_url = 'http://lotterymap.co.kr/sitemap.atom?offset=' + offset.to_s

		args = { ping_url: atom_url }
		uri.query = URI.encode_www_form(args)

		request = Net::HTTP::Post.new(uri.request_uri, header)
		puts http.request(request)
	end

	# Instance methods
	def rank
		ranks.first
	end

	def have_latlng?
		lat.between?(KOREA_LAT_RANGE[:min], KOREA_LAT_RANGE[:max]) && lng.between?(KOREA_LNG_RANGE[:min], KOREA_LNG_RANGE[:max])
	end

	# use with naver, daum search API
	def search_query
		[rank.lottery.name, rank.round_in_ko, rank.rank_in_ko, '당첨'].join(' ')
	end

	def short_addr
		addr.split[0..2].join(' ')
	end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
	before_action :authenticate_user!, except: [:show]

  def index
  end

  def show
		@stores = Store.where(id: params[:id])
		@store = @stores.first
		@rank = @store.rank
		@lottery = @rank.lottery
		@ranks = @lottery.ranks

		respond_to do |format|
			format.html
			format.json { render layout: false }
		end
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/stores_helper.rb
module StoresHelper
	include ActionView::Helpers::NumberHelper

	def news_pub_date(date)
		DateTime.parse(date).strftime("%Y-%m-%d %H:%M")
	end

	def lotto_ball(n)
		content_tag :div, "#{n}", class: ["ball", ball_color(n)]
	end

	def ball_color(n)
		if n > 40
			"green"
		elsif n > 30
			"black"
		elsif n > 20
			"red"
		elsif n > 10
			"blue"
		else
			"yellow"
		end
	end

	def pension_multiplier(num, multiplier)
		number_with_delimiter(num * multiplier)
	end

	def special_number(rank)
		n = rank.rank_nums.find_by_special(true).num
		if n.nil?
			'각조'
		else
			n.to_s + '조'
		end
	end

	def number_or_blank(rank_num)
		rank_num.num.nil? ? '-' : rank_num.num
	end
end

app/views/stores/_lotto.html.erb
<div id="lotto_numbers">
	<% @rank.rank_nums.where(special: false).each do |number| %>
		<%= lotto_ball(number.num) %>
	<% end %>
	<span class="glyphicon glyphicon-plus"></span>
	<div class="special" style="display: inline-block;">
		<%= lotto_ball(@rank.rank_nums.find_by_special(true).num) %>
	</div>
</div>

<h2 class="total_sales gold" style="text-align: center;">&#8361; <%= @lottery.sales_in_won %></h2>
<div class="sales_period">(총 판매액 <%= lotto_sales_period(@lottery) %>)</div>

<div style="margin: 15px -10px;">
	<table class="winners">
		<tbody>
			<tr>
				<th></th>
				<th>당첨자</th>
				<th>당첨금</th>
				<th>당첨 총액</th>
			</tr>
			<% @ranks.each do |rank| %>
				<tr>
					<td style="width: 10%;"><%= rank.rank %>등</td>
					<td style="width: 20%;"><%= rank.winners_in_ko %></td>
					<td style="width: 30%;"><%= rank.winning_in_won(true) %></td>
					<td style="width: 30%;"><%= rank.total_winning_in_won %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/stores/_pension.html.erb
<div style="margin: 15px -10px;">
	<table class="winners">
		<tbody>
			<tr>
				<th></th>
				<th>당첨자</th>
				<th>당첨금</th>
				<th>당첨 총액</th>
			</tr>

			<% 1.upto(7).each do |n| %>
				<tr>
					<% ranks = @ranks.where(rank: n) %>
					<td style="width: 7%;">
						<%= ranks.first.rank %>등 
					</td>
					<td style="width: 23%;"><%= pension_multiplier(ranks.first.total_winners, ranks.count) %>명</td>
					<td style="width: 40%;"><%= ranks.first.winning_in_won %></td>
					<td style="width: 35%;"><%= pension_multiplier(ranks.first.winning * ranks.first.total_winners, ranks.count) %>원</td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

<div style="margin: 15px -10px;">
	<table class="win_numbers">
		<tbody>
			<tr>
				<th style="width: 10%;"></th>
				<th style="width: 90%; text-align: center;" colspan="7">당첨 번호</th>
			</tr>
			<% 1.upto(7).each do |n| %>
				<% @ranks.where(rank: n).each_with_index do |rank, index| %>
					<tr>
						<td style="width: 15%;">
							<% if index == 0 %>
								<%= rank.rank %>등
							<% end %>
						</td>
						<td style="width: 15%;"><%= special_number(rank) %></td>
						<% rank.rank_nums.where("special = 0").each do |number| %>			
							<td style="width: 10%;"><%= number_or_blank(number) %></td>
						<% end %>
					</tr>
				<% end %>
			<% end %>
		</tbody>
	</table>
</div>
		

app/views/stores/_speeto.html.erb
<div style="margin: 15px -10px;">
	<table class="winners">
		<tbody>
			<tr>
				<th></th>
				<th>당첨자</th>
				<th>당첨금</th>
				<th>당첨 총액</th>
			</tr>

			<% 1.upto(2).each do |n| %>
				<% @ranks.where(rank: n).each_with_index do |rank, index| %>
					<tr>
						<td style="width: 8%;">
							<% if index == 0 %>
								<%= rank.rank %>등 
							<% end %>
						</td>
						<td style="width: 17%;"><%= rank.winners_in_ko %></td>
						<td style="width: 45%;"><%= rank.winning_in_won %></td>
						<td style="width: 30%;"><%= rank.total_winning_in_won %></td>
					</tr>
				<% end %>
			<% end %>
		</tbody>
	</table>
</div>

app/views/stores/create.html.erb
<h1>Stores#create</h1>
<p>Find me in app/views/stores/create.html.erb</p>

app/views/stores/destroy.html.erb
<h1>Stores#destroy</h1>
<p>Find me in app/views/stores/destroy.html.erb</p>

app/views/stores/edit.html.erb
<h1>Stores#edit</h1>
<p>Find me in app/views/stores/edit.html.erb</p>

app/views/stores/index.html.erb
<h1>Stores#index</h1>
<p>Find me in app/views/stores/index.html.erb</p>

app/views/stores/new.html.erb
<h1>Stores#new</h1>
<p>Find me in app/views/stores/new.html.erb</p>

app/views/stores/show.html.erb
<div class="container">
	<div class="col-md-6 col-md-offset-3">
		<!-- store -->
		<div style="margin: 0 -20px; text-align: center;">
			<h1 class="win">
				<%= lottery_name_title(@lottery) %> 
				<span class="gold"><%= @rank.round_in_ko %></span>
				<span class="red"><%= @rank.rank_in_ko %></span>
				당첨점
			</h1>
			<% if @lottery.date_exists? %>
				<p class="win_date">(<%= @lottery.date_in_ko %> 추첨)</p>
			<% end %>
			<h2 class="winning">
				<span class="gold">
					<% unless @rank.is_pension? && @rank.rank == 1 %>&#8361; <% end %>
					<%= @rank.winning_in_won %>
				<span>
			</h2>
		</div>

		<!-- map -->
		<div id="naver_map"></div>
		<p class="addr">(위치: <%= @store.addr %>)</p>

		<!-- lottery -->
		<% if @lottery.is_lotto? %>
			<%= render 'lotto' %>
		<% elsif @lottery.is_pension? %>	
			<%= render 'pension' %>
		<% else %>
			<%= render 'speeto' %>
		<% end %>

		<!-- news -->
		<div id="news"></div>

		<%= link_to new_store_store_err_path(@store), remote: true, data: { toggle: "modal", target: "#modal" } do %>
			당첨점 정보가 틀렸나요?
		<% end %>
	</div>
</div>

<script>
	$(document).ready(function() {
		// map
		<% if @store.have_latlng? %>
			loadNaverMap(8)
		<% else %>
			loadNaverMap()
		<% end %>

		// news
		$.ajax({
			url: '<%= news_path %>',
			data: { id: <%= @store.id %> }
		});
	});
</script>

app/views/stores/update.html.erb
<h1>Stores#update</h1>
<p>Find me in app/views/stores/update.html.erb</p>