config/routes.rb
Rails.application.routes.draw do

	# sitemap
	get 'sitemap.xml'  => 'crawlers#google', defaults: { format: 'xml' }
	get 'sitemap.atom' => 'crawlers#naver',  defaults: { format: 'atom' }

	# home
  root 'home#index'

	resources :stores, shallow: true do
		resources :store_errs, only: [:new, :create, :destroy]
	end
	resources :store_errs, only: [:index]
	resources :winners, only: [:index]

	get 'home/change_rounds'
  get 'portals/:id/news' => 'portals#news', as: :news

  devise_for :users, controllers: {
		passwords: "users/passwords",
		registrations: "users/registrations",
		sessions: "users/sessions",
		confirmations: "users/confirmations",
		# unlocks: "users/unlocks",
		# omniauth_callbacks: "users/omniauth_callbacks"
	}

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
		@categories = Category.all
		@rounds = Lottery.where("category_id = 1").pluck(:round).reverse
  end

	def change_rounds
		@rounds = Lottery.category_params(params[:lottery]).pluck(:round).reverse
		respond_to do |format|
			format.js { render layout: false }
		end
	end
end

app/helpers/home_helper.rb
module HomeHelper
	def round(n)
		n.to_s + '회'
	end

	def simple_time_form(time)
		time.strftime("%Y-%m-%d %H시 %M분")
	end
end

app/views/home/change_rounds.js.erb
$("#round").html("<%= 
	j(options_for_select(@rounds.map{ |r| [round(r)] }, nil))
%>")

app/views/home/index.html.erb
<div id="home">
	<div>
		<div class="container" style="color: white;">
			<h1 class="ubuntu">LotteryMap</h1>
			<p>로또(Lotto), 연금복권, 스피또의 
			<br class="visible-xs-inline" />
			당첨통계, 당첨점 검색 서비스</p>
		</div>

		<div class="container">
			<%= form_tag winners_path, id: "winners_search", method: :get do %>
				<div class="form-group">
					<!-- options_for_select(options[text, value], selected) -->
					<div class="col-xs-4 col-xs-offset-2" style="padding: 0 5px 0 0;">
						<%= select_tag :lottery, 
									options_for_select(@categories.map{ |c| [c.short_name] }, nil), 
								  { id: "category", class: "form-control", 
																		onchange: "changeRounds()" } %>
					</div>

					<div class="col-xs-4" style="padding: 0 0 0 5px;">
						<%= select_tag :round, 
									options_for_select(@rounds.map{ |r| [round(r)] }, nil),
																	{ id: "round", class: "form-control" } %>
					</div>
				</div>

				<div class="col-xs-4 col-xs-offset-4">
					<%= button_tag "당첨점 검색", name: nil, class: "btn btn-block" %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/home/stat.html.erb
<div>
	<h3>LOTTO</h3>
	<p>총 판매액(~ 현재)</p>
	<p>&#8361;<%= @total[:sum] %>원</p>
	<% for i in 0..4 %>
		<p><%= i+1 %>등</p>
		<p>총 당첨 금액(인원수)</p>
		<p>&#8361;<%= @sum_of_xth[i].last %>원 (<%= @sum_of_xth[i].first %>명)</p>
		<p>평균 당첨 금액</p>
		<p>&#8361;<%= @avg_of_xth[i] %>원</p>
		<p>가장 큰 당첨 금액</p>
		<p>&#8361;<%= @max_of_xth[i].first %>원 (<%= @max_of_xth[i].last %> 회차)</p>
		<br/>
	<% end %>
	<p>가장 높았던 판매량(~ 현재)</p>
	<p>&#8361;<%= @total[:max] %>원 (<%= @total[:max_round] %> 회차)</p>
</div>