config/routes.rb
Rails.application.routes.draw do

	# sitemap
	get 'sitemap.xml'  => 'crawlers#google', defaults: { format: 'xml' }
	get 'sitemap.atom' => 'crawlers#naver',  defaults: { format: 'atom' }

	# home
  root 'home#index'

	resources :stores, shallow: true do
		resources :store_errs, only: [:new, :create, :destroy]
	end
	resources :store_errs, only: [:index]
	resources :winners, only: [:index]

	get 'home/change_rounds'
  get 'portals/:id/news' => 'portals#news', as: :news

  devise_for :users, controllers: {
		passwords: "users/passwords",
		registrations: "users/registrations",
		sessions: "users/sessions",
		confirmations: "users/confirmations",
		# unlocks: "users/unlocks",
		# omniauth_callbacks: "users/omniauth_callbacks"
	}

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/crawlers_controller.rb
class CrawlersController < ApplicationController
	layout nil

  def google
		@url = 'http://lotterymap.co.kr/'
		@stores = Store.where("updated_at > NOW() - INTERVAL 7 DAY")
		@lotteries = Lottery.all

		respond_to do |format|
			format.xml
		end
  end

	def naver
  	@stores = Store.limit(100).offset(params[:offset].to_i)

		respond_to do |format|
			format.atom
		end
	end
end

app/views/crawlers/google.xml.erb
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">

  <url>
		<loc><%= @url %></loc>
		<changefreq>weekly</changefreq>
	</url>

	<!-- search pages -->
	<% @lotteries.each do |lottery| %>
		<url>
			<loc><%= winners_url(lottery: lottery.category.short_name, round: lottery.round.to_s + '회' ) %></loc>
			<lastmod><%= Time.new(2016, 2, 4).strftime('%Y-%m-%d') %></lastmod>
		</url>
	<% end %>

	<!-- store pages -->
	<% @stores.each do |store| %>
		<url>
			<loc><%= store_url(store) %></loc>
			<lastmod><%= store.updated_at.strftime('%Y-%m-%d') %></lastmod>
		</url>
	<% end %>

</urlset> 