config/routes.rb
Rails.application.routes.draw do

	# sitemap
	get 'sitemap.xml'  => 'crawlers#google', defaults: { format: 'xml' }
	get 'sitemap.atom' => 'crawlers#naver',  defaults: { format: 'atom' }

	# home
  root 'home#index'

	resources :stores, shallow: true do
		resources :store_errs, only: [:new, :create, :destroy]
	end
	resources :store_errs, only: [:index]
	resources :winners, only: [:index]

	get 'home/change_rounds'
  get 'portals/:id/news' => 'portals#news', as: :news

  devise_for :users, controllers: {
		passwords: "users/passwords",
		registrations: "users/registrations",
		sessions: "users/sessions",
		confirmations: "users/confirmations",
		# unlocks: "users/unlocks",
		# omniauth_callbacks: "users/omniauth_callbacks"
	}

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/store_err.rb
class StoreErr < ActiveRecord::Base
	# Associations
  belongs_to :store

	# Scopes
	default_scope { where(active: true) }

	# Validations
	validates :content, presence: true
end

app/controllers/store_errs_controller.rb
class StoreErrsController < ApplicationController
	before_action :authenticate_user!, except: [:new, :create]

  def index
		@store_errs = StoreErr.all
  end

  def new
		@store = Store.find(params[:store_id])
		@store_err = StoreErr.new
		respond_to do |format|
			format.js { render layout: false }
		end
  end

  def create
		@store_err = StoreErr.new(store_err_params)
		if @store_err.save
			flash.now[:success] = "판매점 오류 신고가 접수되었습니다."
		else
			flash.now[:danger] = "내용을 적어주세요."
		end

		respond_to do |format|
			format.js { render layout: false }
		end
  end

  def destroy
		if StoreErr.find(params[:id]).update(active: false)
			flash[:success] = "success"
		else
			flash[:danger] = "fail"
		end
		redirect_to store_errs_url
  end

	private
		def store_err_params
			params.require(:store_err).permit(:store_id, :email, :content)
		end
end

app/views/store_errs/_field.html.erb
<div class="form-group">
	<%= f.label :email, "이메일(선택)" %>
	<%= f.text_field :email, class: "form-control" %>
</div>

<div class="form-group">
	<%= f.label :content, "오류 내용*" %>
	<%= f.text_area :content, { rows: 10, class: "form-control" } %>
</div>

<div class="modal-footer" style="padding: 10px 0 0;">
	<%= f.button "취소", class: "btn btn_cancel", data: { dismiss: "modal" } %>
	<%= f.button "등록", class: "btn btn_submit" %>
</div>

app/views/store_errs/_new.html.erb
<%= form_for [@store, @store_err], remote: true do |f| %>
	<%= f.hidden_field :store_id, value: @store.id %>
	<%= render "store_errs/field", f: f %>
<% end %>

app/views/store_errs/create.js.erb
$('#flash').html("<%= j render 'shared/flash' %>");
$('#modal').modal('hide');

app/views/store_errs/index.html.erb
<table id="report" border="3">
	<tr>
		<th style="min-width: 60px;">id</th>
		<th style="min-width: 200px;">email</th>
		<th style="min-width: 800px;">content</th>
		<th style="min-width: 200px;">created_at</th>
		<th style="min-width: 60px;"></th>
	<tr>
	<% @store_errs.each do |err| %>
		<tr>
			<td><%= err.id %></td>
			<td><%= err.email %></td>
			<td><%= err.content %></td>
			<td><%= simple_time_form(err.created_at) %></td>
			<td><%= link_to "destroy", store_err_path(err), method: :delete %></td>
		</tr>
	<% end %>
</table>

app/views/store_errs/new.js.erb
$(".modal-title").html("판매점 오류 신고")
$(".modal-body").html("<%= j render 'new' %>");